### ISSUE TITLE
missing background colors

### ISSUE THREAD

**Issue by puggan** [mikeerickson/php-cli-colors#1]
ref: https://misc.flogisoft.com/bash/tip_colors_and_formatting

 | Status | nr | name | exemle |
| -- | -- | -- | -- |
| ✔ | 40 | Black | echo -e "Default \e[40mBlack" |  
| ✔ | 41 | Red | echo -e "Default \e[41mRed" |  
| ✔ | 42 | Green | echo -e "Default \e[42mGreen" |  
| ✔ | 43 | Yellow | echo -e "Default \e[43mYellow" |  
| ✔ | 44 | Blue | echo -e "Default \e[44mBlue" |  
| ✔ | 45 | Magenta | echo -e "Default \e[45mMagenta" |  
| ✔ | 46 | Cyan | echo -e "Default \e[46mCyan" |  
| ✔ | 47 | Light gray | echo -e "Default \e[47mLight gray" |  
| | 100 | Dark gray | echo -e "Default \e[100mDark gray" |  
| | 101 | Light red | echo -e "Default \e[101mLight red" |  
| | 102 | Light green | echo -e "Default \e[102mLight green" |  
| | 103 | Light yellow | echo -e "Default \e[103mLight yellow" |  
| | 104 | Light blue | echo -e "Default \e[104mLight blue" |  
| | 105 | Light magenta | echo -e "Default \e[105mLight magenta" |  
| | 106 | Light cyan | echo -e "Default \e[106mLight cyan" |  
| ✔ | 107 | White | echo -e "Default \e[107mWhite" |

**Comment by mikeerickson** [comment]
@puggan PRs are most welcome.  If you don’t have the bandwidth to submit, I will get to it in due time 😊

**Comment by puggan** [comment]
I'l see if I can get the time to do a PR this weekend.

**Comment by mikeerickson** [comment]
Added to 1.11
